### ISSUE TITLE
Contact Info

### ISSUE THREAD

**Issue by tiagosomda** [bmbejcek/fakenews#1]
Hello everyone,
I met you guys at the global ai hackathon and I forgot to get your contact info.
I was on the Dj Neuromancer project.

I was trying to contact you guys, but I forgot to add a note on the linked request.

Next week or so, I will be teaching a workshop about machine learning to some high school kids. I will be just going over a tutorial using Microsoft/Amazon APIs and helping them on the setup. I have very little experience in ML so I thought - why not invite some cool people who really do know their stuff?!

Let me know if you are interested!

**Comment by mayureeb** [comment]
Hey

Thanks for contacting. I would definitely be interested in being a part of
the tutorial. It will be awesome if you can let me know the day and time of
the event.

Best,
Mayuree
